MoviesPage/Models/ErrorViewModel.cs
namespace MoviesPage.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MoviesPage/Models/MovieViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MoviesPage.Models
{
    public class MovieViewModel
    {
        public string ErrorMessage = string.Empty;

        public string SuccessfullMessage = string.Empty;

        public string MovieAlreadyExists = string.Empty;


		[Required(ErrorMessage = "Title is required")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Year is required")]
        public int? Year { get; set; }

        [Required(ErrorMessage = "Genre is required")]
        public string Genre { get; set; }
    }
}

MoviesPage/Controllers/CreateMovieController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesPage.Data;
using MoviesPage.Data.Models;
using MoviesPage.Models;

namespace MoviesPage.Controllers
{
	public class CreateMovieController : Controller
    {
		private readonly MovieDbContext context;

		public CreateMovieController(MovieDbContext dbContext)
		{
			context = dbContext;
		}

		public IActionResult Create()
        {
			var genres = context.Genres.ToList();

			ViewBag.Genres = genres;

			return View();
        }

        [HttpPost]
        public IActionResult OnPost(MovieViewModel movie)
        {
            var genres = context.Genres.ToList();

            ViewBag.Genres = genres;

            if (!ModelState.IsValid)
            {
                movie.ErrorMessage = "Data validation failed!";

                return View(nameof(Create), movie);
            }

            var movies = context.Movies.ToList();
            if (!movies.Any(m => m.Title.ToLower() == movie.Title.ToLower()))
            {
                var newMovie = new Movie()
                {
                    Title = movie.Title,
                    Year = (int)movie.Year,
                };

                var genre = context.Genres.FirstOrDefault(g => g.Id == int.Parse(movie.Genre));
                var movieGenre = new MovieGenre()
                {
                    Genre = genre,
                    Movie = newMovie
                };

                newMovie.Genres.Add(movieGenre);
                context.Movies.Add(newMovie);
                context.SaveChanges();

				movie.SuccessfullMessage = "Your movie was created successfully!";
			}
            else
            {
                movie.MovieAlreadyExists = "This movie already exists!";
            }

            movie.Title = "";
            movie.Year = null;
			ModelState.Clear();

            return View(nameof(Create), movie);
        }
    }
}

MoviesPage/Controllers/DetailsMovieController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesPage.Data;
using MoviesPage.Data.Models;
using MoviesPage.Models;

namespace MoviesPage.Controllers
{
	public class DetailsMovieController : Controller
	{
		private readonly MovieDbContext context;
		private static MovieViewModel _editMovie;

		public DetailsMovieController(MovieDbContext dbContext)
		{
			context = dbContext;
		}

		public IActionResult Details()
		{
			var movies = GetAllMovies();

			return View(movies);
		}

		public IActionResult Select(MovieViewModel movie)
		{
			var movies = GetAllMovies();

			ViewData["SelectedMovie"] = movie;
			return View(nameof(Details), movies);
		}

		public IActionResult Edit(MovieViewModel movie)
		{
			var genres = context.Genres.ToList();

			ViewBag.Genres = genres;

			_editMovie = movie;

			return View(movie);
		}

		[HttpPost]
		public IActionResult OnEditPost(MovieViewModel movie)
		{
			var dbMovie = context.Movies.FirstOrDefault(m => m.Title == _editMovie.Title);
			var movieGenres = context.MoviesGenres.Where(mg => mg.MovieId == dbMovie.Id).ToList();

			if (ModelState.IsValid)
			{
				dbMovie.Title = movie.Title;
				dbMovie.Year = (int)movie.Year;
				dbMovie.Genres.Clear();
				movieGenres.Clear();

				var genre = context.Genres.FirstOrDefault(g => g.Id == int.Parse(movie.Genre));
				dbMovie.Genres.Add(new MovieGenre { Genre = genre, Movie = dbMovie});

				context.SaveChanges();

				var movies = GetAllMovies();

				return View(nameof(Details), movies);
			}

			var genres = context.Genres.ToList();

			ViewBag.Genres = genres;

			return View(nameof(Edit), movie);
		}

		public IActionResult Delete(MovieViewModel movie)
		{
			var dbMovie = context.Movies.FirstOrDefault(m => m.Title == movie.Title);
			context.Movies.Remove(dbMovie);

			context.SaveChanges();

			ViewData["DeletedMovie"] = movie;

			var movies = GetAllMovies();

			return View(nameof(Details), movies);
		}

		private List<MovieViewModel> GetAllMovies()
		{
			return context.Movies
				.Select(m => new MovieViewModel
				{
					Title = m.Title,
					Year = m.Year,
					Genre = m.Genres.Select(g => g.Genre.Name).FirstOrDefault()
				})
				.ToList();
		}
		
	}
}

MoviesPage/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MoviesPage.Models;
using System.Diagnostics;

namespace MoviesPage.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MoviesPage/Views/CreateMovie/Create.cshtml
@model MovieViewModel 

<h3>Create New Movie</h3><br />

@if (Model != null)
{
	@if (Model.ErrorMessage.Length > 0)
	{
		<div class="alert alert-warning alert-dismissible fade show" role="alert">
			<string>@Model.ErrorMessage</string>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	}
	else if (Model.SuccessfullMessage.Length > 0)
	{
		<div class="alert alert-success alert-dismissible fade show" role="alert">
			<string>@Model.SuccessfullMessage</string>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	}
	else if (Model.MovieAlreadyExists.Length > 0)
	{
		<div class="alert alert-danger alert-dismissible fade show" role="alert">
			<string>@Model.MovieAlreadyExists</string>
			<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
		</div>
	}
}

<form asp-controller="CreateMovie" asp-action="OnPost" method="post">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label for="Title">Title:</label>
		<span asp-validation-for="Title" class="text-danger"></span>
		<input type="text" name="Title" value="" placeholder="Title" asp-for="Title" class="form-control" />
	</div>
	<div class="form-group">
		<label for="Year">Year:</label>
		<span asp-validation-for="Year" class="text-danger"></span><br />
		<input type="text" name="Year" placeholder="Year" asp-for="Year" class="form-control" />
	</div>
	<div class="form-group">
		<label for="Genre">Genres:</label>
		<span asp-validation-for="Genre" class="text-danger"></span>
		<select class="form-control" asp-for="Genre">
			@foreach(var genre in ViewBag.Genres)
			{
				<option value="@genre.Id">@genre.Name</option>
			}
		</select>
	</div>
	<div class="submit">
		<br /><input type="submit" name="Submit" value="Submit" /><br />
	</div>
</form>

MoviesPage/Views/DetailsMovie/Details.cshtml
@model List<MovieViewModel>

<h4>Information about all Movies</h4><br />

<h4>Movies count: @Model.Count</h4>

@if (ViewData["SelectedMovie"] != null)
{
	<br /><h5>Selected Movie Details</h5>
	var selectedMovie = ViewData["SelectedMovie"] as MovieViewModel;
	<p>Title: <strong>@selectedMovie.Title</strong></p>
	<p>Year: <strong>@selectedMovie.Year</strong></p>
	<p>Genre: <strong>@selectedMovie.Genre</strong></p>
}
else if (ViewData["DeletedMovie"] != null)
{
	<br /><h5>Deleted Movie Details</h5>
	var deletedMovie = ViewData["DeletedMovie"] as MovieViewModel;
	<p>Title: <strong>@deletedMovie.Title</strong></p>
	<p>Year: <strong>@deletedMovie.Year</strong></p>
	<p>Genre: <strong>@deletedMovie.Genre</strong></p>
}

<table class="table">
	<thead>
		<tr>
			<th>
				@Html.DisplayNameFor(model => model[0].Title)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Year)
			</th>
			<th>
				@Html.DisplayNameFor(model => model[0].Genre)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach(var movie in Model)
		{
			<tr>
				<td>
					@Html.DisplayFor(item => movie.Title)
				</td>
				<td>
					@Html.DisplayFor(item => movie.Year)
				</td>
				<td>
					@Html.DisplayFor(item => movie.Genre)
				</td>
				<td>
					<div class="btn-group">
						<form asp-controller="DetailsMovie" asp-action="Select" method="post" class="form-inline">
							<input type="hidden" name="Title" value="@movie.Title" />
							<input type="hidden" name="Year" value="@movie.Year" />
							<input type="hidden" name="Genre" value="@movie.Genre" />
							<button type="submit" class="btn btn-primary">Select</button>
						</form>
						<div style="margin-left: 5px; margin-right: 5px;"></div>
						<form asp-controller="DetailsMovie" asp-action="Edit" method="post" class="form-inline">
							<input type="hidden" name="Title" value="@movie.Title" />
							<input type="hidden" name="Year" value="@movie.Year" />
							<input type="hidden" name="Genre" value="@movie.Genre" />
							<button type="submit" class="btn btn-warning">Edit </button>
						</form>
						<div style="margin-left: 5px; margin-right: 5px;"></div>
						<form asp-controller="DetailsMovie" asp-action="Delete" method="post" class="form-inline">
							<input type="hidden" name="Title" value="@movie.Title" />
							<input type="hidden" name="Year" value="@movie.Year" />
							<input type="hidden" name="Genre" value="@movie.Genre" />
							<button type="submit" class="btn btn-danger">Delete</button>
						</form>
					</div>
				</td>
			</tr>
		}
	</tbody>
</table>

MoviesPage/Views/DetailsMovie/Edit.cshtml
@model MovieViewModel

<form asp-controller="DetailsMovie" asp-action="OnEditPost" method="post">
	<div asp-validation-summary="ModelOnly" class="text-danger"></div>
	<div class="form-group">
		<label for="Title">Title:</label>
		<span asp-validation-for="Title" class="text-danger"></span>
		<input type="text" name="Title" value="@Model.Title" placeholder="Title" asp-for="Title" class="form-control"/>
	</div>
	<div class="form-group">
		<label for="Year">Year:</label>
		<span asp-validation-for="Year" class="text-danger"></span>
		<input type="text" name="Year" value="@Model.Year" placeholder="Year" asp-for="Year" class="form-control"/>
	</div>
	<div class="form-group">
		<label for="Genre">Genres:</label>
		<span asp-validation-for="Genre" class="text-danger"></span>
		<select class="form-control" asp-for="Genre">
			@foreach (var genre in ViewBag.Genres)
			{
				if (genre.Name == Model.Genre)
				{
					<option value="@genre.Id" selected>@genre.Name</option>
				}
				else
				{
					<option value="@genre.Id">@genre.Name</option>
				}
			}
		</select>
	</div><br />
	<button type="submit" class="btn btn-primary" name="Save">Save</button>
</form>

MoviesPage/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>

    <h4>This is and ASP.NET simple Movies Page application.</h4>

    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MoviesPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoviesPage</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoviesPage.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoviesPage</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @* Added new list item in the navigation bar for Creating new Movie *@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CreateMovie" asp-action="Create">Create Movie</a>
                        </li>
                        @* Added new list item for details about all movies *@
                        <li class="nav-item"> 
                            <a class="nav-link text-dark" asp-area="" asp-controller="DetailsMovie" asp-action="Details">Movies Information</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MoviesPage - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>